disabled_rules:
- line_length
- trailing_whitespace
- nesting
- function_parameter_count
- function_body_length
- cyclomatic_complexity
- type_body_length
- file_length
- identifier_name
- large_tuple
excluded:
- Pods
- NADA-iOS-forRelease/Sources/AppDelegate.swift
- NADA-iOS-forRelease/Sources/SceneDelegate.swift

