disabled_rules:
- line_length
- trailing_whitespace
- nesting
- function_parameter_count
- function_body_length
- cyclomatic_complexity
excluded:
- Pods
- NADA-iOS-forRelease/Sources/AppDelegate.swift
- NADA-iOS-forRelease/Sources/SceneDelegate.swift

