# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "NADA-iOS-forRelease.xcodeproj")
    build_app(workspace: "NADA-iOS-forRelease.xcworkspace", scheme: "NADA-iOS-forRelease")
    upload_to_app_store

  # error
  error do |lane, exception, options|
    version = get_version_number(
                target: "NADA-iOS-forRelease"
              )
    build = get_build_number 

    slack(
      username: "fastlane",
      icon_url: "https://github.com/hyun99999/algorithm-Swift/assets/69136340/f997e95e-3c09-432b-aa35-9c67ea381e0d",
      message: "에러 발생!!! 발생!!🚨 : #{exception}",
      success: false,
      slack_url: "https://hooks.slack.com/services/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",
      payload: {
	"Version": version + "(" + build + ")"
      }
    )
  end
end
